---
- platform: template
  switches:
    clean_bumper:
      friendly_name: Clean Bumper
      entity_id: input_boolean.vacuum_ready_to_clean
      value_template: "{{ is_state('input_boolean.vacuum_ready_to_clean', 'on')}}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.vacuum_ready_to_clean
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.vacuum_ready_to_clean
