---
- platform: template
  switches:
    garage_door:
      friendly_name: Garage Door Switch
      entity_id: switch.garage_door
      value_template: "{{ is_state('binary_sensor.garage_door_detector_sensor', 'on')}}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.garage_relay_1
      turn_off:
        service: switch.turn_on
        data:
          entity_id: switch.garage_relay_1
