language: python
cache: pip
python:
  - "3.7"
install:
  - "pip3 install homeassistant"
script:
  - "mv secrets.yaml.sample secrets.yaml"
  - "mkdir custom_components"
  - "mkdir -p /config/scripts"
  - "mkdir -p /config/automation"
  - "chmod -R 777 /config"
  - "git clone https://github.com/twrecked/hass-aarlo.git"
  - "mv hass-aarlo/custom_components/aarlo custom_components/"
  - "hass --version"
  - "hass -c . --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"'
