- alias: 'Rule 1 Light on in evening'
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: light.turn_on
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level

- alias: 'Rule 1 Light off before bed'
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: light.turn_off
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level

- alias: 'Rule 1 Light on in morning'
  trigger:
    - platform: time
      at: '05:30:00'
  action:
    service: light.turn_on
    entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level

- alias: 'Rule 1 Light off after sunrise'
  trigger:
    - platform: sun
      event: sunrise
      offset: '01:00:00'
  action:
    service: light.turn_off
    entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level

#- alias: 'Rule 2 Upstairs Cooling Nighttime'
#  trigger:
#    - platform: time
#      at: '23:00:00'
#  action:
#    - service: climate.set_temperature
#      entity_id: climate.linear_tbz48_thermostat_cooling_1_3_2
#      data:
#        temperature: 78
#
#    - service: climate.set_temperature
#      entity_id: climate.linear_tbz48_thermostat_heating_1_3_1
#      data:
#        temperature: 68
#
#- alias: 'Rule 2 Upstairs Cooling Morning'
#  trigger:
#    - platform: time
#      at: '05:00:00'
#  action:
#    - service: climate.set_temperature
#      entity_id: climate.linear_tbz48_thermostat_cooling_1_3_2
#      data:
#        temperature: 76
#
#    - service: climate.set_temperature
#      entity_id: climate.linear_tbz48_thermostat_heating_1_3_1
#      data:
#        temperature: 70




