homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 33.4483
  longitude: -81.6921
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 137
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize:
    climate.linear_tbz48_thermostat_cooling_1_3_2:
      friendly_name: Upstairs Cooling
    climate.linear_tbz48_thermostat_heating_1_3_1:
      friendly_name: Upstairs Heating
    sensor.linear_tbz48_thermostat_temperature_3_1:
      friendly_name: Upstairs Temp
    climate.linear_tbz48_thermostat_cooling_1_4_2:
      friendly_name: Downstairs Cooling
    climate.linear_tbz48_thermostat_heating_1_4_1:
      friendly_name: Downstairs Heating
    sensor.linear_tbz48_thermostat_temperature_4_1:
      friendly_name: Downstairs Temp
    light.linear_lb60z1_dimmable_led_light_bulb_level_2_0:
      friendly_name: Office Lamp Light

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
    api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

sensor:
  - platform: yr
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
        - temperature
  - platform: yahoo_finance
    symbols:
      - VFFVX
      - PARFX

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    home_interval: 60
    track_new_devices: no
  - platform: owntracks
#  - platform: asuswrt
#    host: 192.168.1.1
#    username: admin
#    password: !secret asus_password
#    protocol: telnet

mqtt:
  broker: localhost
  port: 8883
  client_id: home-assistant-1
  keepalive: 60
  username: hass
  password: !secret http_password
  certificate: /etc/mosquitto/conf.d/ca.crt
  protocol: 3.1

zone:
  name: Home
  latitude: 33.479498
  longitude: -81.716718
  radius: 100
  icon: mdi:account-multiple

zone 2:
  name: SRS
  latitude: 33.268602
  longitude: -81.620638
  radius: 15000
  icon: mdi:flask-outline

zone 3:
  name: CHOG
  latitude: 33.471181
  longitude: -81.987698
  radius: 200
  icon: mdi:hospital-building

media_player:
  - platform: roku
    host: 192.168.1.33
  - platform: roku
    host: 192.168.1.165
  - platform: roku
    host: 192.168.1.186

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.2-py3.4-linux-armv7l.egg/config

notify:
  - name: Hass
    platform: pushbullet
    api_key: !secret pushbullet_api_key

script: !include scripts.yaml

automation: !include automation.yaml
