---
homeassistant:
  packages: !include_dir_named integrations/
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes/

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
# zone: !include zones.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
switch: !include_dir_merge_list switches/

http:
  base_url: https://hass.kail.io:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# which rokus are which?
# 192.168.2.59
# 192.168.2.26 - Kitchen
# 192.168.2.29 - Garage
# 192.168.2.120 - TV Room
# 192.168.2.82 - Bedroom
roku:
  - host: 192.168.2.59
  - host: 192.168.2.26
  - host: 192.168.2.29
  - host: 192.168.2.120
  - host: 192.168.2.82

notify:
  - name: Hass
    platform: pushbullet
    api_key: !secret pushbullet_api_key

namecheapdns:
  host: hass
  domain: kail.io
  password: !secret namecheap_access_token

input_select:
  andrew_status_dropdown:
    name: Andrew
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
  maggie_status_dropdown:
    name: Maggie
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

  presence:
    name: Presence
    options:
      - Home
      - Away
      - Extended Away
  guest_mode:
    name: Guests
    options:
      - Yes
      - No

ecovacs:
  username: !secret ecovacs_username
  password: !secret ecovacs_password
  country: !secret ecovacs_country
  continent: !secret ecovacs_continent

blink:
  username: !secret blink_username
  password: !secret blink_password
  scan_interval: 300
  binary_sensors:
    monitored_conditions:
      - motion_enabled
      - motion_detected
  sensors:
    monitored_conditions:
      - battery
      - temperature

tplink:
  discovery: false
  switch:
    - host: 192.168.2.87
    - host: 192.168.2.91

unifi:
  controllers:
    - host: 192.168.1.236
      site: Default
      detection_time: 150

alexa:
  smart_home:
# filter:
#   exclude_entities:
#     - script.arm_off
# entity_config:
#   script.arm_away:
#     name: Away Mode
#     description: Set alarms to away mode
#   script.arm_home:
#     name: Night Mode
#     description: Set alarms to night mode

# broadlink
# 78:0f:77:00:51:66

light:
  - platform: flux_led
    devices:
      192.168.2.126:
        name: TV LED Strip
        protocol: 'ledenet'
      192.168.2.128:
        name: Everett's Crib
        protocol: 'ledenet'

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
