homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 33.4483
  longitude: -81.6921
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 137
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# recorder settings
recorder:
  purge_interval: 7
  purge_keep_days: 7
  db_url: sqlite:///data/haconfig/home_assistant.db

config:

http:
  # Uncomment this to add a password (recommended!)
    api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
    base_url: example.duckdns.org
    ssl_certificate: /etc/letsencrypt/live/hass.kail.io/fullchain.pem
    ssl_key: /etc/letsencrypt/live/hass.kail.io/privkey.pem

# enable map
map:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

sensor: !include sensor.yaml

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/22
    home_interval: 60
    track_new_devices: no
  - platform: owntracks_http

zone: !include zones.yaml

media_player:
  - platform: roku
    host: 192.168.2.29
  - platform: roku
    host: 192.168.2.30
  - platform: roku
    host: 192.168.2.38

zwave:
  usb_path: /dev/ttyACM0

notify:
  - name: Hass
    platform: pushbullet
    api_key: !secret pushbullet_api_key

script: !include scripts.yaml

automation: !include automation.yaml

namecheapdns:
    host: hass
    domain: kail.io
    password: !secret namecheap_access_token

input_select:
    house_mode:
        name: House Mode
        options:
            - Morning
            - Day
            - Evening
            - Night
    presense:
        name: Presence
        options:
            - Home
            - Away
