---
- platform: yr
- platform: version

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - temperature
    - precip_accumulation
    - precip_probability
    - precip_intensity

- platform: statistics
  entity_id: sensor.dark_sky_precip_intensity
  precision: 3
  max_age:
    days: 7

- platform: template
  sensors:
    andrew_status:
      value_template: '{{ states.input_select.andrew_status_dropdown.state }}'
      friendly_name: 'Andrew'
    maggie_status:
      value_template: '{{ states.input_select.maggie_status_dropdown.state }}'
      friendly_name: 'Maggie'
    alarm_mode:
      value_template: '{{ states.input_select.alarm_mode.state }}'
      friendly_name: 'Alarm Mode'
