---
- alias: "AC Stuff"
  trigger:
    - platform: time
      at: '20:00:00'
    - platform: time
      at: '22:00:00'
    - platform: time
      at: '07:00:00'
    - platform: state
      entity_id: input_select.presence
    - platform: state
      entity_id: input_select.guest_mode
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.downstairs_ac
        temperature: >
          {%- if now().hour >= 7 and now().hour < 20 %}
            {%- if is_state('input_select.presence', 'Home') %}
              73
            {%- elif is_state('input_select.presence', 'Away') %}
              75
            {%- else %}
              77
            {%- endif %}
          {%- else %}
            {%- if is_state('input_select.presence', 'Home') %}
              71
            {%- elif is_state('input_select.presence', 'Away') %}
              73
            {%- else %}
              78
            {%- endif %}
          {%- endif %}
    - service: climate.set_temperature
      data_template:
        entity_id: climate.upstairs_ac
        target_temp_high: >
          {%- if now().hour >= 7 and now().hour < 22 %}
            {%- if is_state('input_select.guest_mode', 'True') %}
            74
            {%- else %}
              {%- if is_state('input_select.presence', 'Home') %}
              73
              {%- elif is_state('input_select.presence', 'Away') %}
              75
              {%- else %}
              77
              {%- endif %}
            {%- endif %}

          {%- else %}
            {%- if is_state('input_select.guest_mode', 'True') %}
            72
            {%- else %}
            74
            {%- endif %}
          {%- endif %}

        target_temp_low: >
          {%- if now().hour >= 7 and now().hour < 22 %}
            {%- if is_state('input_select.guest_mode', 'True') %}
            67
            {%- else %}
              {%- if is_state('input_select.presence', 'Home') %}
                68
              {%- elif is_state('input_select.presence', 'Away') %}
                66
              {%- else %}
                64
              {%- endif %}
            {%- endif %}

          {%- else %}
            {%- if is_state('input_select.guest_mode', 'True') %}
              69
            {%- else %}
              64
            {%- endif %}
          {%- endif %}

    - delay: '00:01:00'
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: |
            Dowstairs set to {{state_attr('climate.downstairs_ac', 'temperature')}}
            Upstairs set to {{state_attr('climate.upstairs_ac', 'target_temp_low')}}/{{state_attr('climate.upstairs_ac', 'target_temp_high')}}


#    - service: climate.set_temperature
#      data_template:
#        entity_id: climate.upstairs_ac
#        target_temp_high: >
#          {%- if now().hour >= 7 and now().hour < 22 %}
#            {%- if is_state('input_select.guest_mode', 'True') %}
#            74
#            {%- else %}
#              {%- if is_state('input_select.presence', 'Home') %}
#              74
#              {%- elif is_state('input_select.presence', 'Away') %}
#              76
#              {%- else %}
#              78
#              {%- endif %}
#            {%- endif %}
#
#          {%- else %}
#            {%- if is_state('input_select.guest_mode', 'True') %}
#            72
#            {%- else %}
#            78
#            {%- endif %}
#          {%- endif %}
#
#        target_temp_low: >
#          {%- if now().hour >= 7 and now().hour < 22 %}
#            {%- if is_state('input_select.guest_mode', 'True') %}
#            67
#            {%- else %}
#              {%- if is_state('input_select.presence', 'Home') %}
#                68
#              {%- elif is_state('input_select.presence', 'Away') %}
#                66
#              {%- else %}
#                64
#              {%- endif %}
#            {%- endif %}
#
#          {%- else %}
#            {%- if is_state('input_select.guest_mode', 'True') %}
#              69
#            {%- else %}
#              64
#            {%- endif %}
#          {%- endif %}
