---
- alias: "AC Stuff"
  trigger:
    - platform: time
      at: '20:00:00'
    - platform: time
      at: '07:00:00'
    - platform: time
      at: '02:00:00'
    - platform: time
      at: '17:00:00'
    - platform: state
      entity_id: input_select.presence
    - platform: state
      entity_id: input_select.guest_mode
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.downstairs_ac
        temperature: >

          {%- if now().hour >= 2 and now().hour < 7 %}
            {%- if is_state('input_select.presence', 'Home') %}
              72
            {%- elif is_state('input_select.presence', 'Away') %}
              75
            {%- else %}
              78
              {%- endif %}

          {%- elif now().hour >= 7 and now().hour < 17 %}
            {%- if is_state('input_select.presence', 'Home') %}
              75
            {%- elif is_state('input_select.presence', 'Away') %}
              76
            {%- else %}
              78
            {%- endif %}

          {%- elif now().hour >= 17 and now().hour < 20 %}
            {%- if is_state('input_select.presence', 'Home') %}
              73
            {%- elif is_state('input_select.presence', 'Away') %}
              75
            {%- else %}
              78
            {%- endif %}

          {%- else %} # between 8 and 2
            {%- if is_state('input_select.presence', 'Home') %}
              71
            {%- elif is_state('input_select.presence', 'Away') %}
              75
            {%- else %}
              78
            {%- endif %}
          {%- endif %}


    - service: climate.set_temperature
      data_template:
        entity_id: climate.upstairs_ac
        target_temp_high: >
          {%- if now().hour >= 2 and now().hour < 7 %}
            {%- if is_state('input_select.guest_mode', 'True') %}
              73
            {%- else %}
              {%- if is_state('input_select.presence', 'Home') %}
                73
              {%- elif is_state('input_select.presence', 'Away') %}
                75
              {%- else %}
                78
              {%- endif %}
            {%- endif %}

          {%- elif now().hour >= 7 and now().hour < 17 %}
            {%- if is_state('input_select.guest_mode', 'True') %}
              74
            {%- else %}
              {%- if is_state('input_select.presence', 'Home') %}
                75
              {%- elif is_state('input_select.presence', 'Away') %}
                77
              {%- else %}
                78
              {%- endif %}
            {%- endif %}

          {%- elif now().hour >= 17 and now().hour < 20 %}
            {%- if is_state('input_select.guest_mode', 'True') %}
              73
            {%- else %}
              {%- if is_state('input_select.presence', 'Home') %}
                73
              {%- elif is_state('input_select.presence', 'Away') %}
                75
              {%- else %}
                78
              {%- endif %}
            {%- endif %}

          {%- else %} # between 8 and 2
            {%- if is_state('input_select.guest_mode', 'True') %}
              73
            {%- else %}
              {%- if is_state('input_select.presence', 'Home') %}
                73
              {%- elif is_state('input_select.presence', 'Away') %}
                75
              {%- else %}
                78
              {%- endif %}
            {%- endif %}
          {%- endif %}
        target_temp_low: >
          {%- if is_state('input_select.guest_mode', 'True') %}
            69
          {%- else %}
            {%- if is_state('input_select.presence', 'Home') %}
              68
            {%- elif is_state('input_select.presence', 'Away') %}
              66
            {%- else %}
              64
            {%- endif %}
          {%- endif %}

    - delay: '00:01:00'
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: |
            Dowstairs set to {{state_attr('climate.downstairs_ac', 'temperature')}}
            Upstairs set to {{state_attr('climate.upstairs_ac', 'target_temp_low')}}/{{state_attr('climate.upstairs_ac', 'target_temp_high')}}
