- alias: 'Upstairs Cooling Nighttime'
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: climate.set_temperature
      entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_cooling_1
      data:
        temperature: 78

    - service: climate.set_temperature
      entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1
      data:
        temperature: 66

- alias: 'Upstairs Cooling Morning'
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    - service: climate.set_temperature
      entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_cooling_1
      data:
        temperature: 76

    - service: climate.set_temperature
      entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1
      data:
        temperature: 68
