---
- alias: "Weekly Snapshots"
  trigger:
    - platform: time
      at: '00:00:00'
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: auto_backup.snapshot_full
      data:
        keep_days: 14
