---
- alias: 'Blink Updates'
  trigger:
    - platform: time_pattern
      hours: "*"
  action:
    - service: blink.trigger_camera
      data:
        name: camera.blink_back_patio
    - delay: '00:04:00'
    - service: blink.trigger_camera
      data:
        name: camera.blink_driveway
    - delay: '00:04:00'
    - service: blink.trigger_camera
      data:
        name: camera.blink_front_porch
    - delay: '00:04:00'
    - service: blink.trigger_camera
      data:
        name: camera.blink_garage
