---
- alias: "Auto update from git"
  trigger:
    - platform: state
      entity_id: sensor.akail_homeassistant_last_build_state
      from: started
      to: passed
  condition:
    - condition: state
      entity_id: input_select.git_update_mode
      state: 'Auto Restart'
  action:
    - service: hassio.addon_start
      data:
        addon: core_git_pull
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: Updating git from passed build



- alias: "Update  scripts"
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: deleted
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: moved
  condition:
    - condition: state
      entity_id: sensor.akail_homeassistant_last_build_state
      state: passed
    - condition: template
      value_template: {{ '/config/scripts' in trigger.event.data.folder }}
  action:
    - service: notify.tbot
      data:
        title: Home Assistant
        message: Updating scripts on passed build
    - service: script.reload
    
- alias: "Update automations"
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: deleted
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: moved
  condition:
    - condition: state
      entity_id: sensor.akail_homeassistant_last_build_state
      state: passed
    - condition: template
      value_template: {{ '/config/automation' in trigger.event.data.folder }}
  action:
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: Updating automations on passed build
    - service: automation.reload
