---
- alias: "Auto update from git"
  trigger:
    - platform: state
      entity_id: sensor.akail_homeassistant_last_build_state
      from: started
      to: passed
  condition:
    - condition: state
      entity_id: input_select.git_update_mode
      state: 'Auto Reload'
  action:
    - service: hassio.addon_start
      data:
        addon: core_git_pull
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: Updating git from passed build

- alias: "Auto update from git and restart"
  trigger:
    - platform: state
      entity_id: sensor.akail_homeassistant_last_build_state
      from: started
      to: passed
  condition:
    - condition: state
      entity_id: input_select.git_update_mode
      state: 'Auto Restart'
  action:
    - service: hassio.addon_start
      data:
        addon: core_git_pull
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: Updating git from passed build and restarting
    - service: homeassistant.restart

- alias: "Update  scripts"
  trigger:
    - platform: event
      event_type: folder_watcher
  condition:
    - condition: state
      entity_id: sensor.akail_homeassistant_last_build_state
      state: passed
    - condition: template
      value_template: "{{ '/config/scripts' in trigger.event.data.folder }}"
    - condition: state
      entity_id: input_select.git_update_mode
      state: 'Auto Reload'
  action:
    - service: notify.tbot
      data:
        title: Home Assistant
        message: Updating scripts on passed build
    - service: script.reload
    
- alias: "Update automations"
  trigger:
    - platform: event
      event_type: folder_watcher
  condition:
    - condition: state
      entity_id: sensor.akail_homeassistant_last_build_state
      state: passed
    - condition: template
      value_template: "{{ '/config/automation' in trigger.event.data.folder }}"
    - condition: state
      entity_id: input_select.git_update_mode
      state: 'Auto Reload'
  action:
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: Updating automations on passed build
    - service: automation.reload
