---
- alias: "Auto update from git"
  trigger:
    - platform: state
      entity_id: sensor.akail_homeassistant_last_build_state
      from: started
      to: passed
  condition:
    - condition: state
      entity_id: input_select.git_update_mode
      state: 'Auto Restart'
  action:
    - service: hassio.addon_start
      data:
        addon: core_git_pull
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: Updating git from passed build



- alias: "Update  scripts"
  trigger:
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: modified
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: deleted
    - platform: event
      event_type: folder_watcher
      event_data:
        event_type: moved
  action:
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: {{ trigger.event.data.folder }}
          #{% if "/config/scripts" in trigger.event.data.folder %}
            #Updating scripts on passed build
          #{% elif "/config/automation" in trigger.event.data.folder %}
            #Updating automations on passed build
          #{% else %}
            #Unidentified folder found
          #{% endif %}
  #condition:
    #- condition: state
      #entity_id: sensor.akail_homeassistant_last_build_state
      #state: passed
    #- condition: or
      #conditions:
        #- condition: template
          #value_template: "{{ '/config/scripts' in trigger.event.data.folder }}"
        #- condition: template
          #value_template: "{{ '/config/automation' in trigger.event.data.folder }}"

