- alias: 'Light on in evening'
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: light.turn_on
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level

- alias: 'Light off before bed'
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: light.turn_off
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level

- alias: 'Light on in morning'
  trigger:
    - platform: time
      at: '05:00:00'
  action:
    - service: light.turn_on
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level

- alias: 'Light off after sunrise'
  trigger:
    - platform: sun
      event: sunrise
      offset: '01:00:00'
  action:
    - service: light.turn_off
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level

- alias: 'Hutch light on before sunset'
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2
        brightness_pct: 35

- alias: 'Hutch light on at sunset'
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2
        brightness_pct: 65


- alias: 'Hutch light off before bed'
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    - service: light.turn_off
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2
