---
- alias: 'Restart Modem'
  trigger:
    - platform: time
      at: '03:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.modem
    - delay: '00:00:30'
    - service: switch.turn_on
      entity_id: switch.modem
