---
# This will turn on the light between 5 and 1 hour after sunrise
# When the bedroom door has been opened
- alias: 'Atrium light on in morning'
  trigger:
    - platform: time
      at: '06:00:00'
    - platform: state
      entity_id: binary_sensor.master_bedroom_door
      from: 'off'
      to: 'on'
  condition:
    condition: sun
    after: sunrise
    after_offset: '01:00:00'
  action:
    - service: light.turn_on
      entity_id: light.atrium

- alias: 'Atrium light off after sunrise'
  trigger:
    - platform: sun
      event: sunrise
      offset: '01:00:00'
  action:
    - service: light.turn_off
      entity_id: light.atrium

- alias: 'Atrium night light'
  trigger:
    platform: state
    entity_id: binary_sensor.master_bedroom_door
    from: 'off'
    to: 'on'
  condition:
    - condition: time
      after: '22:00:00'
      before: '5:00:00'
  action:
    - service: light.turn_on
      entity_id: light.atrium
    - delay: '00:05:00'
    - service: light.turn_off
      entity_id: light.atrium
