---
- alias: "Printing LEDs On"
  trigger:
    - platform: state
      entity_id: binary_sensor.creality_3v2_printing
      to: on
  action:
    - service: light.turn_on
      entity_id: light.desk_leds
      data:
        brightness_pct: 90

- alias: "Printing LEDs Off"
  trigger:
    - platform: state
      entity_id: binary_sensor.creality_3v2_printing
      to: off
  action:
    - service: light.turn_off
      entity_id: light.desk_leds
