---
- alias: "Printing LEDs On"
  trigger:
    - platform: state
      entity_id: binary_sensor.creality_3v2_printing
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.desk_leds
      data:
        brightness_pct: 90

- alias: "Printing LEDs Off"
  trigger:
    - platform: state
      entity_id: binary_sensor.creality_3v2_printing
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.desk_leds

- alias: "Printer off after 30 minutes"
  trigger:
    - platform: state
      entity_id: binary_sensor.creality_3v2_printing
      to: 'off'
      for:
        minutes: 30
  action:
    - service: switch.turn_off
      entity_id: switch.ender_printer
    - service: light.turn_off
      entity_id: light.desk_leds
