---
- alias: Security Away Mode
  trigger:
    - platform: state
      entity_id: input_select.presence
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.presence
        state: 'Extended Away'
      - condition: state
        entity_id: input_select.presence
        state: 'Away'
  action:
    - service: script.blink_away

- alias: Security Home Mode
  trigger:
    - platform: state
      entity_id: input_select.presence

  condition:
    - condition: state
      entity_id: input_select.presence
      state: 'Home'
  action:
    - service: script.blink_home
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: Security home activated

- alias: Blink night mode
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: script.blink_away

- alias: Blink morning mode
  trigger:
    - platform: time
      at: '05:30:00'
  action:
    - service: script.blink_home

- alias: 'Security off after waking up'
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_door
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: '05:30:00'
      before: '07:00:00'
    - condition: state
      entity_id: alarm_control_panel.2_gippy_ct_alarm_control_panel
      state: "armed_home"
    - condition: state
      entity_id: input_select.presence
      state: 'Home'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.2_gippy_ct_alarm_control_panel
