---
- alias: "Speed Test Check"
  trigger:
    - platform: numeric_state
      entity_id: sensor.speedtest_download
      below: 50
    - platform: numeric_state
      entity_id: sensor.speedtest_upload
      below: 4
    - platform: numeric_state
      entity_id: sensor.speedtest_ping
      above: 100
  action:
    - service: notify.tbot
      data_template:
        title: Home Assistant
        message: |
          Speedtest Issue 
          Ping {{states('sensor.speedtest_ping')}} ms
          Download  {{states('sensor.speedtest_download')}} Mbit/s
          Upload {{states('sensor.speedtest_upload')}} Mbit/s
