---
- alias: 'TV LED Color'
  trigger:
    - platform: state
      entity_id: media_player.tcl_tv
  condition:
    - condition: template
      value_template: "{{ states('media_player.tcl_tv') != 'standby'}}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.tv_led_strip
        color_name: >
          {%- if is_state_attr('media_player.tcl_tv', 'source', 'Home') %}
          orangered
          {%- elif is_state_attr('media_player.tcl_tv', 'source', 'Hulu') %}
          green
          {%- elif is_state_attr('media_player.tcl_tv', 'source', 'Spotify Music') %}
          green
          {%- elif is_state_attr('media_player.tcl_tv', 'source', 'Netflix') %}
          red
          {%- elif is_state_attr('media_player.tcl_tv', 'source', 'Disney Plus') %}
          blue
          {%- elif is_state_attr('media_player.tcl_tv', 'source', 'YouTube') %}
          red
          {%- else %}
          orangered
          {%- endif %}

- alias: "TV LED Off"
  trigger:
    - platform: state
      entity_id: media_player.tcl_tv
  condition:
    - condition: template
      value_template: "{{ states('media_player.tcl_tv') == 'standby'}}"
  action:
    - service: light.turn_off
      data:
        entity_id: light.tv_led_strip

- alias: "TV Room Lights On"
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_room_motion
      to: on
  condition:
    - condition: template
      value_template: "{{ states('media_player.tcl_tv') == 'standby'}}"
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.test_tplink
    - service: switch.turn_on
      data:
        entity_id: switch.andrews_tv_room_lamp

- alias: "TV Room Lights Off"
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_room_motion
      to: off
      for:
        minutes: 5
  condition:
    - condition: template
      value_template: "{{ states('media_player.tcl_tv') == 'standby'}}"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.test_tplink
    - service: switch.turn_off
      data:
        entity_id: switch.andrews_tv_room_lamp


