---
- alias: 'Run Vacuum'
  trigger:
    - platform: time
      at: '14:30:00'
  condition:
    - condition: time
      weekday:
        - mon
        - wed
        - fri
    - condition: not
      conditions:
        - condition: state
          entity_id: input_select.presence
          state: Extended Away
    - condition: state
      entity_id: binary_sensor.master_bedroom_door
      state: 'off'
  action:
    - service: notify.tbot
      data:
        title: Home Assistant
        message: "Running vacuum"
    - service: vacuum.turn_on
      entity_id: vacuum.bumper
    - delay: '02:00:00'
    - service: vacuum.return_to_base
      entity_id: vacuum.bumper
