- alias: 'Run Vacuum'
  trigger:
    - platform: time
      at: '15:15:00'
  condition:
    - condition: time
      weekday:
        - mon
        - wed
        - fri
#    - condition: state
#      entity_id: binary_sensor.bedroom_door_status
#      state: 'off'
  action:
    - service: notify.andrews_phone
      data:
        message: "Running vacuum"
    - service: vacuum.turn_on
      entity_id: vacuum.none
    - delay: '01:15:00'
    - service: vacuum.return_to_base
      entity_id: vacuum.none
