---
# - platform: template
#   sensors:
#     bedroom_door_status:
#       friendly_name: 'Bedroom Door'
#       device_class: opening
#       value_template: >-
#         {%- if is_state('sensor.hank_hkzwdws01_doorwindow_sensor_access_control', '22') -%}
#         true
#         {%- else -%}
#         false
#         {%- endif -%}

- platform: aarlo
  monitored_conditions:
  - motion
  - sound
  - ding

- platform: template
  sensors:
    tv_room_motion:
      friendly_name: "TV Room Motion"
      device_class: motion
      value_template: >-
        {{states('sensor.tv_room_pir_motion_sensor_alarm_level') |int > 200 }}

- platform: workday
  country: US

- platform: rpi_power
