- platform: flux_led
  devices:
    192.168.2.126:
      name: TV LED Strip
      protocol: 'ledenet'
    192.168.2.128:
      name: Everett's Crib
      protocol: 'ledenet'
    192.168.2.141:
      name: Desk LEDs
      protocol: 'ledenet'

- platform: group
  name: Master Bedroom Lights
  entities:
    - light.andrew_bedside_lamp
    - light.maggies_bedside_lamp
    - light.bedroom_lamp

- platform: group
  name: TV Room Lights
  entities:
    - light.andrews_tv_room_light
    - light.maggies_tv_room_light
