---
- platform: yr

- platform: version

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - temperature
    - precip_accumulation
    - precip_probability
    - precip_intensity
    - alerts
    - humidity
    - cloud_cover

- platform: statistics
  entity_id: sensor.dark_sky_precip_intensity
  precision: 3
  max_age:
    days: 7

- platform: template
  sensors:
    andrew_status:
      value_template: '{{ states.input_select.andrew_status_dropdown.state }}'
      friendly_name: 'Andrew'
    maggie_status:
      value_template: '{{ states.input_select.maggie_status_dropdown.state }}'
      friendly_name: 'Maggie'
    alarm_mode:
      value_template: '{{ states.input_select.alarm_mode.state }}'
      friendly_name: 'Alarm Mode'

# Arlo baby camera
- platform: aarlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality

- platform: travisci
  api_key: !secret github_api_key
  branch: master
  repository:
    - homeassistant

- platform: glances
  host: 127.0.0.1
  port: 61209
  version: 3
  resources:
    - 'processor_load'
    - 'memory_use_percent'
    - 'disk_use_percent'

- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - 76561198024717521
