---
- platform: yr

- platform: version

- platform: uptime

- platform: season

- platform: template
  sensors:
    andrew_status:
      value_template: '{{ states.input_select.andrew_status_dropdown.state }}'
      friendly_name: 'Andrew'
    maggie_status:
      value_template: '{{ states.input_select.maggie_status_dropdown.state }}'
      friendly_name: 'Maggie'
    alarm_mode:
      value_template: '{{ states.input_select.alarm_mode.state }}'
      friendly_name: 'Alarm Mode'

# Arlo baby camera
- platform: aarlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality

- platform: travisci
  api_key: !secret github_api_key
  branch: master
  repository:
    - homeassistant

- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - 76561198024717521


# Tracking entity to entity
- platform: waze_travel_time
  name: "Maggie to home"
  origin: device_tracker.maggie_s_iphone
  destination: zone.home
  region: 'US'

- platform: rpi_power
  text_state: true

- platform: time_date
  display_options:
    - 'time'
