---
- platform: version

- platform: uptime

- platform: season

- platform: template
  sensors:
    andrew_status:
      value_template: '{{ states.input_select.andrew_status_dropdown.state }}'
      friendly_name: 'Andrew'
    maggie_status:
      value_template: '{{ states.input_select.maggie_status_dropdown.state }}'
      friendly_name: 'Maggie'
    alarm_mode:
      value_template: '{{ states.input_select.alarm_mode.state }}'
      friendly_name: 'Alarm Mode'
    last_alexa:
      value_template: >
        {{ expand(states.group.echos) | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}

# Arlo baby camera
- platform: aarlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality

- platform: travisci
  api_key: !secret github_api_key
  branch: master
  repository:
    - homeassistant

- platform: steam_online
  api_key: !secret steam_api_key
  accounts:
    - 76561198024717521


# Tracking entity to entity
- platform: waze_travel_time
  name: "Andrew to home"
  origin: device_tracker.moto_g_6
  destination: zone.home
  region: 'US'


# Tracking entity to entity
- platform: waze_travel_time
  name: "Maggie to home"
  origin: device_tracker.maggie_s_iphone_3
  destination: zone.home
  region: 'US'


- platform: time_date
  display_options:
    - 'time'

- platform: statistics
  entity_id: sensor.myups_load
