esphome:
  name: office
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: KingdomKail
  password: bluewingtape

  ap:
    ssid: "Office Fallback Hotspot"
    password: "Y65z8CupW8BN"

  manual_ip:
    static_ip: 192.168.2.140
    gateway: 192.168.2.1
    subnet: 255.255.255.0

api:

# Enable logging

logger:

#captive_portal:

ota:

sensor:
  - platform: dht
    pin: D7
    temperature:
      name: "Multisensor Temperature"
    humidity:
      name: "Multisensor Humidity"
  - platform: adc
    pin: A0
    name: "Multisensor Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Multisensor Motion"
    device_class: motion

output:
  - platform: esp8266_pwm
    pin: D1
    id: redgpio
  - platform: esp8266_pwm
    pin: D2
    id: greengpio
  - platform: esp8266_pwm
    pin: D3
    id: bluegpio

light:
  - platform: rgb
    name: "Multisensor Light"
    red: redgpio
    green: greengpio
    blue: bluegpio
